export const products = [
    {
        id: 1,
        categoria: "tortasclasicas",
        image: "https://i.postimg.cc/0ypqQdNj/brownie.jpg",
        name: "Brownie clásico",
        description: "Base húmeda de chocolate intenso,dulce de leche.crema chantillí, merengue italiano y nueces. Tamaño 20 cm rinde 8 porciones aproximadamente.",
        price: 4000,
        stock: 10,
    },
    {
        id: 2,
        categoria: "tortasclasicas",
        image: "https://i.postimg.cc/1XgkZDT9/cheescake.jpg",
        name: "Cheesecake de frutos rojos",
        description: "Base de vainilla, crema cocida de queso decorado con salsa de frutos rojos y más frutos rojos. Tamaño 20 cm rinde 8 porciones aproximadamente.",
        price: 3800,
        stock: 10,
    },
    {
        id:3,
        categoria: "tortasclasicas",
        image: "https://i.postimg.cc/tJLLRYQF/lemonpie.jpg",
        name: "Lemon Pie",
        description: "Base de masa vainilla, curd de limón y merengue italiano. Medida: 24 cm.",
        price: 3400,
        stock:10,
    },
    {
        id:4,
        categoria: "tortasclasicas",
        image: "https://i.postimg.cc/Nj8WYsNr/rogel.jpg",
        name: "Rogel",
        description: "Mil hojas de dulce de leche. Medida: 20 cm.",
        price: 3500,
        stock:10,
    },
    {
        id:5,
        categoria: "numericas",
        image: "https://i.postimg.cc/RFpk8ggs/number.jpg",
        name: "Number/Letter Cake",
        description: "Es una chocotorta, por dentro crema de queso y dulce de leche con galletitas chocolinas,oreo o ambas. Decorada con chocolates. Precio por unidad (numero o letra)",
        price: 4100,
        stock:10,
    },
    {
        id:6,
        categoria: "apedido",
        image: "https://i.postimg.cc/JnhwPf5H/matilda.jpg",
        name: "Torta Matilda",
        description: "Bizcocho húmedo de cacao rellena y cubierta pro una crema de chocolate.Tamaño 20 cm rinde 8 porciones aproximadamente.",
        price: 4600,
        stock:4,
    },
    {
        id:7,
        categoria: "apedido",
        image: "https://i.postimg.cc/h46F13zh/redvelvet.jpg",
        name: "Red Velvet",
        description: "Red velvet bizcocho húmedo y suave de cacao, relleno y cubierto por una crema de queso y chocolate blanco.Tamaño 20 cm rinde 8 porciones aproximadamente.",
        price: 5300,
        stock:3,
    }
]